#Create
POST http://localhost:8082/api/web/analytics/event
Content-Type: application/json
Project-Id: 4

{
  "name": "item_pageview",
  "pathEligible": true
}

###

#Get By Id
GET http://localhost:8082/api/web/analytics/event/5
Content-Type: application/json
Project-Id: 4

###

#Get All
GET http://localhost:8082/api/web/analytics/event
Content-Type: application/json
Project-Id: 2

###

#Delte By Id
DELETE http://localhost:8082/api/web/analytics/event/5
Content-Type: application/json
Project-Id: 2