#Create
POST http://localhost:8082/api/web/analytics/funnel
Content-Type: application/json
Project-Id: 2

{
  "productNumber": 2,
  "name": "first cro funnel",
  "steps": [
    {
      "eventName": "login",
      "stepNumber": 0,
      "stepConditions": [
        {
          "eventProperty": "hhh",
          "eventPropertyType": "NUMBER",
          "value": "122223",
          "negate": "true",
          "operator": "EQUAL"
        },
        {
          "eventProperty": "hhh",
          "eventPropertyType": "NUMBER",
          "value": "12223,4",
          "negate": "true",
          "operator": "NOT_BETWEEN"
        },
        {
          "eventProperty": "hhh",
          "eventPropertyType": "TEXT",
          "value": "1223",
          "negate": "true",
          "operator": "ENDS_WITH"
        }
      ]
    },
    {
      "eventName": "logout",
      "stepNumber": 1,
      "stepConditions": [
        {
          "eventProperty": "hhh",
          "eventPropertyType": "TEXT",
          "value": "123",
          "negate": "false",
          "operator": "GREATER_THAN_OR_EQUAL"
        }
      ]
    }
  ]
}


###

#Update
PUT http://localhost:8082/api/web/analytics/funnel
Content-Type: application/json
Project-Id: 2

{
  "id": 43,
  "name": "3333 cro funnel",
  "productNumber": 2,
  "steps": [
    {
      "id": 117,
      "eventName": "asdf",
      "stepNumber": 0,
      "stepConditions": [
        {
          "id": 202,
          "operator": "EQUAL",
          "value": "122223",
          "negate": "true",
          "eventProperty": "hhh",
          "eventPropertyType": "TEXT"
        },
        {
          "id": 203,
          "operator": "NOT_BETWEEN",
          "value": "12223,4",
          "negate": "true",
          "eventPropertyType": "TEXT",
          "eventProperty": "hhh"
        },
        {
          "id": 204,
          "operator": "ENDS_WITH",
          "value": "1223",
          "negate": "true",
          "eventPropertyType": "TEXT",
          "eventProperty": "hhh"
        }
      ]
    },
    {
      "id": 118,
      "eventName": "3333",
      "stepNumber": 1,
      "stepConditions": [
        {
          "id": 205,
          "operator": "GREATER_THAN_OR_EQUAL",
          "value": "123",
          "negate": "true",
          "eventPropertyType": "TEXT",
          "eventProperty": "asdfsadf"
        }
      ]
    }
  ]
}

###

#Get By Id
GET http://localhost:8082/api/web/analytics/funnel/60
Content-Type: application/json
Project-Id: 2

###

#Get All
GET http://localhost:8082/api/web/analytics/funnel
Content-Type: application/json
Project-Id: 2

###

#Delte By Id
DELETE http://localhost:8082/api/web/analytics/funnel/11
Content-Type: application/json
Project-Id: 2

###
GET http://localhost:8082/api/web/analytics/funnel/contains/?page=0&size=10
Project-Id: 2

###

#Query By Id
GET http://localhost:8082/api/web/analytics/funnel/59/query
Content-Type: application/json
Project-Id: 2