spring:
  application:
    name: Analytics API
  profiles:
    active: dev,default
  datasource:
    url: jdbc:postgresql://localhost:5432/cro_analytics
    username: cro_analytics_username
    password: cro_analytics_password
    driver-class-name: org.postgresql.Driver
  secondDatasource:
    url: jdbc:clickhouse://cro-stage-1:8123
    username: crouser
    password: crostage
    driver-class-name: cc.blynk.clickhouse.ClickHouseDriver
  jpa:
    database: default
    hibernate:
      ddl-auto: update # TODO: add liquibase for database migrations
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
