POST http://localhost:8081/api/web/cro/collector/receive
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZHRyYWNlX3Byb2plY3RfMSIsImV4cCI6MTY5MzI0MjY1MiwiaWF0IjoxNjkzMjEzODUyfQ.Wj530sybcweH_1BrJPgWAOvYWyZ1jbOZlb-xxhz3_S_fLbdfjeaHgVi_Bqn4UCyioOw_gEnGegJjE-5w7dVQyQ

{
  "id": 1,
  "productId": 2,
  "appVersion": "{\"hi\":\"aaa\"}",
  "deviceType": "11"
}

###
GET http://localhost:8081/api/web/cro/collector/return-type
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZHRyYWNlX3Byb2plY3RfMSIsImV4cCI6MTY5MzI0MjY1MiwiaWF0IjoxNjkzMjEzODUyfQ.Wj530sybcweH_1BrJPgWAOvYWyZ1jbOZlb-xxhz3_S_fLbdfjeaHgVi_Bqn4UCyioOw_gEnGegJjE-5w7dVQyQ
