POST http://localhost:8081/api/web/cro/collector/receive
content-Type: application/json

{
  "id": 1,
  "businessId": 2,
  "appVersion": "{\"hi\":\"aaa\"}",
  "deviceType": "11"
}

###
POST http://localhost:8081/api/web/cro/collector/table

###
GET http://localhost:8081/api/web/cro/collector

###
POST http://localhost:8081/api/web/cro/collector/parquet