POST http://localhost:8081/api/web/cro/product
content-Type: application/json

{
  "description": "adtrace project",
  "name": "Adtrace"
}

###
GET http://localhost:8081/api/web/cro/product

###
GET http://localhost:8081/api/web/cro/product/1

###
POST http://localhost:8081/api/web/cro/product/schema
content-Type: application/json

{
  "id": 1,
  "businessId": 2,
  "data": {
    "appVersion": "string",
    "deviceType": "int"
  }
}
