POST http://localhost:8081/api/web/cro/user
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZHRyYWNlX3Byb2plY3RfMSIsImV4cCI6MTY5MzI0MjY1MiwiaWF0IjoxNjkzMjEzODUyfQ.Wj530sybcweH_1BrJPgWAOvYWyZ1jbOZlb-xxhz3_S_fLbdfjeaHgVi_Bqn4UCyioOw_gEnGegJjE-5w7dVQyQ

{
  "name": "Adtrace",
  "username": "adtrace_1",
  "password": "1111"
}

###
GET http://cro-stage-1:8081/api/web/cro/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJpbnRyYWNrXzMiLCJleHAiOjE2OTQxMDg2MjAsImlhdCI6MTY5MzgyODYyMH0.XYeYfSdMnZvM95kd3zqioi27OFEHriG7wBlYc-ET4xGE6zwi0V3MZZVvhE4TrTuoW67S1Bli_vP4qCfOofO4eg

###
GET http://cro-stage-1:8081/api/web/cro/user/14
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJpbnRyYWNrXzMiLCJleHAiOjE2OTQxMDg2MjAsImlhdCI6MTY5MzgyODYyMH0.XYeYfSdMnZvM95kd3zqioi27OFEHriG7wBlYc-ET4xGE6zwi0V3MZZVvhE4TrTuoW67S1Bli_vP4qCfOofO4eg

###
POST http://localhost:8081/api/web/cro/user/schema
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJpbnRyYWNrXzMiLCJleHAiOjE2OTM4NjMxNzAsImlhdCI6MTY5MzgzNDM3MH0.47s-nySA9tGdl8OH0aUpKlnYF5QUpy_KQEztcRnwNzMqKBajQeJLdNilL5B8_F6SyNwxrNMmhZq4CVjMNsW-jg

{
  "data": {
    "product_id":"STRING",
    "user_id":"STRING",
    "timestamp":"NUMBER",
    "event_name":"STRING"
  }
}
