spring:
  application:
    name: CRO Storage
  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    password: cro_analytics_password
    username: cro_analytics_username
    driver-class-name: org.postgresql.Driver
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
    listener:
      ack-mode: manual
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

server:
  port: 8081
#spring.kafka.consumer.enable-auto-commit=true

