POST http://localhost:8081/api/web/cro/gateway/write
content-Type: application/json

{
  "message":"hello everyone",
  "name": "Kamand Torkzaban",
  "age": 25
}

###
POST http://localhost:8081/api/web/cro/gateway/table
###
GET http://localhost:8081/api/web/cro/gateway